import { createRouter } from '@tanstack/react-router'
import type { QueryClient } from '@tanstack/react-query'
import type { AuthUser } from '@/types/api'
// routeTree is auto-generated by the TanStack Router Vite plugin on first `pnpm dev`
import { routeTree } from './routeTree.gen'

export interface RouterContext {
  queryClient: QueryClient
  user: AuthUser | null
}

export const router = createRouter({
  routeTree,
  context: {
    queryClient: undefined!,
    user: null,
  },
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
