"""Database repository package.

All repository interfaces and their SQLAlchemy implementations are exported
from this package. Existing imports throughout the codebase continue to work
unchanged (e.g. ``from ...infrastructure.database.repositories import SQLAlchemyUserRepository``).

The full implementation lives in ``_base.py``. Future work can split that
module into per-domain files (e.g. ``user.py``, ``lead.py``) and update the
re-exports here — without touching any router or use-case code.
"""

from ._base import (
    # Abstractions
    ActivityRepository,
    AgentRepository,
    AppointmentRepository,
    AvailabilityRepository,
    CallHistoryRepository,
    DepartmentRepository,
    InvoiceRepository,
    LeadAddressRepository,
    LeadRepository,
    MembershipRepository,
    MembershipUnavailabilityRepository,
    NoteRepository,
    NotificationLogRepository,
    NotificationTypeRepository,
    OrganizationRepository,
    OrgNotificationRecipientRepository,
    ReminderRepository,
    ScenarioRepository,
    ScheduleRepository,
    SelectedCalendarRepository,
    TagBaseRepository,
    TaskRepository,
    TranscriptRepository,
    TransferRepository,
    TradeCategoryRepository,
    TradeServiceRepository,
    UserRepository,
    # SQLAlchemy implementations
    SQLAlchemyActivityRepository,
    SQLAlchemyAgentRepository,
    SQLAlchemyAppointmentRepository,
    SQLAlchemyAvailabilityRepository,
    SQLAlchemyCallHistoryRepository,
    SQLAlchemyDepartmentRepository,
    SQLAlchemyInvoiceRepository,
    SQLAlchemyLeadAddressRepository,
    SQLAlchemyLeadRepository,
    SQLAlchemyMembershipRepository,
    SQLAlchemyMembershipUnavailabilityRepository,
    SQLAlchemyNoteRepository,
    SQLAlchemyNotificationLogRepository,
    SQLAlchemyNotificationTypeRepository,
    SQLAlchemyOrganizationRepository,
    SQLAlchemyOrgNotificationRecipientRepository,
    SQLAlchemyReminderRepository,
    SQLAlchemyScenarioRepository,
    SQLAlchemyScheduleRepository,
    SQLAlchemySelectedCalendarRepository,
    SQLAlchemyTagBaseRepository,
    SQLAlchemyTaskRepository,
    SQLAlchemyTranscriptRepository,
    SQLAlchemyTransferRepository,
    SQLAlchemyTradeCategoryRepository,
    SQLAlchemyTradeServiceRepository,
    SQLAlchemyUserRepository,
)

__all__ = [
    # Abstractions
    "ActivityRepository",
    "AgentRepository",
    "AppointmentRepository",
    "AvailabilityRepository",
    "CallHistoryRepository",
    "DepartmentRepository",
    "InvoiceRepository",
    "LeadAddressRepository",
    "LeadRepository",
    "MembershipRepository",
    "MembershipUnavailabilityRepository",
    "NoteRepository",
    "NotificationLogRepository",
    "NotificationTypeRepository",
    "OrganizationRepository",
    "OrgNotificationRecipientRepository",
    "ReminderRepository",
    "ScenarioRepository",
    "ScheduleRepository",
    "SelectedCalendarRepository",
    "TagBaseRepository",
    "TaskRepository",
    "TranscriptRepository",
    "TransferRepository",
    "TradeCategoryRepository",
    "TradeServiceRepository",
    "UserRepository",
    # SQLAlchemy implementations
    "SQLAlchemyActivityRepository",
    "SQLAlchemyAgentRepository",
    "SQLAlchemyAppointmentRepository",
    "SQLAlchemyAvailabilityRepository",
    "SQLAlchemyCallHistoryRepository",
    "SQLAlchemyDepartmentRepository",
    "SQLAlchemyInvoiceRepository",
    "SQLAlchemyLeadAddressRepository",
    "SQLAlchemyLeadRepository",
    "SQLAlchemyMembershipRepository",
    "SQLAlchemyMembershipUnavailabilityRepository",
    "SQLAlchemyNoteRepository",
    "SQLAlchemyNotificationLogRepository",
    "SQLAlchemyNotificationTypeRepository",
    "SQLAlchemyOrganizationRepository",
    "SQLAlchemyOrgNotificationRecipientRepository",
    "SQLAlchemyReminderRepository",
    "SQLAlchemyScenarioRepository",
    "SQLAlchemyScheduleRepository",
    "SQLAlchemySelectedCalendarRepository",
    "SQLAlchemyTagBaseRepository",
    "SQLAlchemyTaskRepository",
    "SQLAlchemyTranscriptRepository",
    "SQLAlchemyTransferRepository",
    "SQLAlchemyTradeCategoryRepository",
    "SQLAlchemyTradeServiceRepository",
    "SQLAlchemyUserRepository",
]
