/**
 * LiveKit utilities and helpers
 */

export interface LiveKitConfig {
  url: string
  token: string
  roomName: string
}

/**
 * Generate participant token (if needed separately)
 */
export function generateParticipantToken(
  _roomName: string,
  _participantName: string
): string {
  // This would typically call the backend API
  // For now, tokens are generated by the backend
  return ''
}
