"""phase1_core_schema_extensions

Revision ID: b7b7548ea359
Revises: 
Create Date: 2026-02-12 16:17:47.867746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b7548ea359'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('invited_email', sa.String(length=255), nullable=True))
    op.add_column('membership', sa.Column('is_disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('membership', sa.Column('is_point_of_escalation', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('membership', sa.Column('scheduling_priority', sa.Integer(), nullable=True))
    op.add_column('membership', sa.Column('responsibility', sa.Text(), nullable=True))
    op.add_column('membership', sa.Column('personalisation_notes', sa.Text(), nullable=True))
    op.alter_column('membership', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('organization', sa.Column('stripe_plan', sa.String(length=50), nullable=True))
    op.add_column('organization', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('default_schedule_id', sa.Integer(), nullable=True))
    op.add_column('organization', sa.Column('public_scheduler_configurations', sa.JSON(), nullable=True))
    op.add_column('organization', sa.Column('tag', sa.String(length=50), nullable=True))
    op.add_column('organization', sa.Column('seats', sa.Integer(), nullable=True))
    op.add_column('organization', sa.Column('addons', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('email_verified', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('phone_verified', sa.BigInteger(), nullable=True))

    # Phase 1 new tables
    op.create_table(
        'membership_unavailability',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('member_id', sa.String(length=36), nullable=False),
        sa.Column('start_date', sa.BigInteger(), nullable=True),
        sa.Column('end_date', sa.BigInteger(), nullable=True),
        sa.Column('start_time', sa.BigInteger(), nullable=True),
        sa.Column('end_time', sa.BigInteger(), nullable=True),
        sa.Column('recurrence_type', sa.String(length=20), nullable=True),
        sa.Column('days_of_week', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['member_id'], ['membership.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'session',
        sa.Column('session_token', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('expires', sa.BigInteger(), nullable=False),
        sa.Column('impersonating_from_user_id', sa.String(length=36), nullable=True),
        sa.Column('active_membership_id', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['active_membership_id'], ['membership.id'], ),
        sa.ForeignKeyConstraint(['impersonating_from_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('session_token'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('membership_unavailability')
    op.drop_column('user', 'phone_verified')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'role')
    op.drop_column('user', 'phone')
    op.drop_column('organization', 'addons')
    op.drop_column('organization', 'seats')
    op.drop_column('organization', 'tag')
    op.drop_column('organization', 'public_scheduler_configurations')
    op.drop_column('organization', 'default_schedule_id')
    op.drop_column('organization', 'stripe_customer_id')
    op.drop_column('organization', 'stripe_plan')
    op.alter_column('membership', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('membership', 'personalisation_notes')
    op.drop_column('membership', 'responsibility')
    op.drop_column('membership', 'scheduling_priority')
    op.drop_column('membership', 'is_point_of_escalation')
    op.drop_column('membership', 'is_disabled')
    op.drop_column('membership', 'invited_email')
    # ### end Alembic commands ###
